//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        public APPLICATION()
        {
            this.INTERVIEW_SCHEDULES = new HashSet<INTERVIEW_SCHEDULES>();
        }
    
        public int job_id { get; set; }
        public int seeker_id { get; set; }
        public Nullable<System.DateTime> applied_date { get; set; }
        public string status { get; set; }
        public int application_id { get; set; }
        public string RejectionFeedback { get; set; }
    
        public virtual JOB_SEEKER_PROFILE JOB_SEEKER_PROFILE { get; set; }
        public virtual JOB JOB { get; set; }
        public virtual ICollection<INTERVIEW_SCHEDULES> INTERVIEW_SCHEDULES { get; set; }
    }
}
