//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYER
    {
        public EMPLOYER()
        {
            this.JOBS = new HashSet<JOB>();
        }
    
        public int employer_id { get; set; }
        public string company_name { get; set; }
        public string industry { get; set; }
        public string company_description { get; set; }
        public string website { get; set; }
        public string location { get; set; }
        public string companyLogo { get; set; }
    
        public virtual ICollection<JOB> JOBS { get; set; }
        public virtual USER USER { get; set; }
    }
}
