//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERVIEW_SCHEDULES
    {
        public int interview_id { get; set; }
        public int application_id { get; set; }
        public string interview_type { get; set; }
        public System.DateTime interview_date { get; set; }
        public string location_or_link { get; set; }
        public string interviewer_name { get; set; }
        public string interviewer_email { get; set; }
        public string notes_for_seeker { get; set; }
        public string internal_notes { get; set; }
        public string interview_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
    }
}
