//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public JOB()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.SAVED_JOBS = new HashSet<SAVED_JOBS>();
            this.JOB_SKILLS = new HashSet<JOB_SKILLS>();
        }
    
        public int employer_id { get; set; }
        public string job_title { get; set; }
        public string job_description { get; set; }
        public string requirements { get; set; }
        public string location { get; set; }
        public string salary_range { get; set; }
        public string job_type { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string status { get; set; }
        public int job_id { get; set; }
    
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        public virtual EMPLOYER EMPLOYER { get; set; }
        public virtual ICollection<SAVED_JOBS> SAVED_JOBS { get; set; }
        public virtual ICollection<JOB_SKILLS> JOB_SKILLS { get; set; }
    }
}
