//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_SEEKER_PROFILE
    {
        public JOB_SEEKER_PROFILE()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
            this.SAVED_JOBS = new HashSet<SAVED_JOBS>();
            this.USER_SKILLS = new HashSet<USER_SKILLS>();
        }
    
        public int seeker_id { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string experience_level { get; set; }
        public string education { get; set; }
        public string resume_file { get; set; }
        public string Bio { get; set; }
        public string ProfilePicturePath { get; set; }
    
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        public virtual ICollection<SAVED_JOBS> SAVED_JOBS { get; set; }
        public virtual ICollection<USER_SKILLS> USER_SKILLS { get; set; }
        public virtual USER USER { get; set; }
    }
}
