//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_SKILLS
    {
        public int job_skill_id { get; set; }
        public int job_id { get; set; }
        public int skillID { get; set; }
    
        public virtual JOB JOB { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
