//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION
    {
        public int notification_id { get; set; }
        public int user_id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string read_status { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
