//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAVED_JOBS
    {
        public int seeker_id { get; set; }
        public int job_id { get; set; }
        public Nullable<System.DateTime> saved_at { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
    
        public virtual JOB_SEEKER_PROFILE JOB_SEEKER_PROFILE { get; set; }
        public virtual JOB JOB { get; set; }
    }
}
