//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.USER_SKILLS = new HashSet<USER_SKILLS>();
            this.JOB_SKILLS = new HashSet<JOB_SKILLS>();
        }
    
        public string skillName { get; set; }
        public int SkillID { get; set; }
    
        public virtual ICollection<USER_SKILLS> USER_SKILLS { get; set; }
        public virtual ICollection<JOB_SKILLS> JOB_SKILLS { get; set; }
    }
}
