//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SKILLS
    {
        public int JobSeekerSkillID { get; set; }
        public Nullable<int> seeker_id { get; set; }
        public int SkillID { get; set; }
    
        public virtual JOB_SEEKER_PROFILE JOB_SEEKER_PROFILE { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
