//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Portal_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.NOTIFICATIONS = new HashSet<NOTIFICATION>();
        }
    
        public string full_name { get; set; }
        public string email { get; set; }
        public string password_hash { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string username { get; set; }
        public int UserId { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual EMPLOYER EMPLOYER { get; set; }
        public virtual JOB_SEEKER_PROFILE JOB_SEEKER_PROFILE { get; set; }
        public virtual ICollection<NOTIFICATION> NOTIFICATIONS { get; set; }
    }
}
